[package]
name = "webapi-bin"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
webapi-lib = { path = "../webapi-lib" }
